# Bybit Trading Bot Configuration

# Bybit API Configuration
# ⚠️ ВАЖНО: API ключи загружаются из переменных окружения (.env файл)
# НИКОГДА не храните реальные ключи в этом файле!
api:
  exchange: "bybit"
  # api_key и api_secret загружаются из .env файла через SecureConfig
  testnet: true  # Use Bybit testnet for development
  base_url: "https://api-testnet.bybit.com"  # Testnet URL
  # base_url: "https://api.bybit.com"  # Mainnet URL

# Trading Parameters
trading:
  symbol: "BTCUSDT"  # Trading pair
  category: "linear"  # linear, inverse, option, spot
  timeframe: "1"     # 1, 3, 5, 15, 30, 60, 120, 240, 360, 720, D, W, M
  position_size: 0.02  # 2% of portfolio per trade
  max_positions: 2    # Maximum number of concurrent positions
  leverage: 2          # SAFE leverage for futures trading (max 2x for beginners)
  margin_mode: "isolated"  # isolated or cross

# Risk Management
risk:
  stop_loss: 0.015    # 1.5% stop loss
  take_profit: 0.03   # 3% take profit
  max_daily_loss: 0.05  # 5% maximum daily loss
  max_drawdown: 0.15    # 15% maximum drawdown
  max_position_size: 0.1  # 10% maximum position size
  equity_stop: 0.2     # Stop trading at 20% equity loss

# Technical Indicators (optimized for intraday)
indicators:
  # Moving Averages
  sma_periods: [5, 10, 20, 50]
  ema_periods: [8, 13, 21, 34]
  
  # Momentum
  rsi_period: 14
  rsi_overbought: 70
  rsi_oversold: 30
  
  # MACD
  macd_fast: 12
  macd_slow: 26
  macd_signal: 9
  
  # Bollinger Bands
  bb_period: 20
  bb_std: 2
  
  # Stochastic
  stoch_k: 14
  stoch_d: 3
  
  # ATR for volatility
  atr_period: 14
  
  # Volume indicators
  obv_period: 10
  vwap_period: 20

# Machine Learning Configuration
ml:
  enabled: true
  model_type: "lstm"  # lstm, gru, xgboost, lightgbm
  features: ["price", "volume", "rsi", "macd", "bb", "atr"]
  lookback_window: 60
  prediction_horizon: 5  # minutes
  retrain_frequency: 24  # hours
  confidence_threshold: 0.6

# Strategy Configuration
strategy:
  name: "ml_enhanced_intraday"
  enabled: true
  parameters:
    # Trend following
    trend_threshold: 0.3
    volume_threshold: 1.5
    
    # Mean reversion
    reversion_threshold: 0.7
    oversold_threshold: 25
    overbought_threshold: 75
    
    # Breakout
    breakout_threshold: 0.8
    volume_spike_threshold: 2.0
    
    # Grid trading
    grid_enabled: false
    grid_levels: 10
    grid_spacing: 0.005

# Intraday Trading Settings
intraday:
  trading_hours: "24/7"  # Crypto markets are 24/7
  session_start: "00:00"
  session_end: "23:59"
  max_trades_per_day: 50
  min_trade_interval: 300  # 5 minutes between trades
  scalping_enabled: true
  scalping_timeframe: "1"  # 1-minute scalping

# Backtesting Configuration
backtesting:
  enabled: true
  start_date: "2023-01-01"
  end_date: "2024-01-01"
  initial_capital: 10000
  commission: 0.001  # 0.1% commission
  slippage: 0.002   # 0.2% realistic slippage for crypto futures

# Logging
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file: "logs/bybit_trading_bot.log"
  max_size: "50MB"
  backup_count: 10
  console_output: true

# Database
database:
  type: "sqlite"  # sqlite, postgresql
  path: "data/bybit_trading_bot.db"
  backup_interval: "6h"
  trade_history_days: 365

# Monitoring and Alerts
monitoring:
  enabled: true
  telegram_bot_token: "your_telegram_bot_token"
  telegram_chat_id: "your_telegram_chat_id"
  alert_on_trade: true
  alert_on_error: true
  alert_on_daily_summary: true

# Performance Optimization
performance:
  websocket_reconnect_interval: 5
  api_rate_limit: 120  # requests per minute
  data_cache_size: 1000
  parallel_processing: true
  max_workers: 4
